type: collection.insomnia.rest/5.0
name: My first collection
meta:
  id: wrk_2e0ccdc63a6f4134a4ff6367db97a5bb
  created: 1753132623493
  modified: 1753132623493
  description: ""
collection:
  - url: "{{ _.base_url }}/products"
    name: Get all Products
    meta:
      id: req_6945611108e5475db17155021e9fd926
      created: 1753132623517
      modified: 1753132806898
      isPrivate: false
      description: ""
      sortKey: -1753132727768
    method: GET
    headers:
      - name: User-Agent
        value: insomnia/11.3.0
    settings:
      renderRequestBody: true
      encodeUrl: true
      followRedirects: global
      cookies:
        send: true
        store: true
      rebuildPath: true
  - url: "{{ _.base_url }}/products"
    name: Create a Product
    meta:
      id: req_c932eb23dcf846fd984219482e44591a
      created: 1753132697887
      modified: 1753133050502
      isPrivate: false
      description: ""
      sortKey: -1753132727693
    method: POST
    body:
      mimeType: application/json
      text: >-
        {
        	"name": "{% faker 'commerce', '', '', '', 'productName', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'en' %}",
        	"price": {% faker 'random', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'numeric', '', '', '', '', '', 'en' %}
        }
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/11.3.0
    settings:
      renderRequestBody: true
      encodeUrl: true
      followRedirects: global
      cookies:
        send: true
        store: true
      rebuildPath: true
  - url: "{{ _.base_url }}/products/3"
    name: Get a Product
    meta:
      id: req_b1f4b6c487914cdba60fd52e8775e54b
      created: 1753132707675
      modified: 1753132951694
      isPrivate: false
      description: ""
      sortKey: -1753132727718
    method: GET
    headers:
      - name: User-Agent
        value: insomnia/11.3.0
    settings:
      renderRequestBody: true
      encodeUrl: true
      followRedirects: global
      cookies:
        send: true
        store: true
      rebuildPath: true
  - url: "{{ _.base_url }}/products/3"
    name: Update a Product
    meta:
      id: req_6bf14c8753f24f69a0bb5d6fd9a687c1
      created: 1753132718103
      modified: 1753133092343
      isPrivate: false
      description: ""
      sortKey: -1753132727680.5
    method: PUT
    body:
      mimeType: application/json
      text: >-
        {
        	"name": "{% faker 'commerce', '', '', '', 'productName', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'en' %}"
        }
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/11.3.0
    settings:
      renderRequestBody: true
      encodeUrl: true
      followRedirects: global
      cookies:
        send: true
        store: true
      rebuildPath: true
  - url: "{{ _.base_url }}/products/3"
    name: Remove a Product
    meta:
      id: req_b978b30d671144679784f60ee37bab3c
      created: 1753132727668
      modified: 1753133104472
      isPrivate: false
      description: ""
      sortKey: -1753132727668
    method: DELETE
    headers:
      - name: User-Agent
        value: insomnia/11.3.0
    settings:
      renderRequestBody: true
      encodeUrl: true
      followRedirects: global
      cookies:
        send: true
        store: true
      rebuildPath: true
cookieJar:
  name: Default Jar
  meta:
    id: jar_4baa0d791cf3c941883494cd34db4623cec28acc
    created: 1753132623496
    modified: 1753132623496
environments:
  name: Base Environment
  meta:
    id: env_4baa0d791cf3c941883494cd34db4623cec28acc
    created: 1753132623495
    modified: 1753132669542
    isPrivate: false
  data:
    base_url: http://localhost:5000/v1
