-- DropForeignKey
ALTER TABLE `CATEGORIA` DROP FOREIGN KEY `CATEGORIA_ibfk_1`;

-- DropForeignKey
ALTER TABLE `CLIENTE_ENDERECO` DROP FOREIGN KEY `CLIENTE_ENDERECO_ibfk_1`;

-- DropForeignKey
ALTER TABLE `CLIENTE_ENDERECO` DROP FOREIGN KEY `CLIENTE_ENDERECO_ibfk_2`;

-- DropForeignKey
ALTER TABLE `COMPRA` DROP FOREIGN KEY `COMPRA_ibfk_1`;

-- DropForeignKey
ALTER TABLE `COMPRA` DROP FOREIGN KEY `COMPRA_ibfk_2`;

-- DropForeignKey
ALTER TABLE `COMPRA_PRODUTOS` DROP FOREIGN KEY `COMPRA_PRODUTOS_ibfk_1`;

-- DropForeignKey
ALTER TABLE `COMPRA_PRODUTOS` DROP FOREIGN KEY `COMPRA_PRODUTOS_ibfk_2`;

-- DropForeignKey
ALTER TABLE `PRODUTOS` DROP FOREIGN KEY `PRODUTOS_ibfk_1`;

-- DropForeignKey
ALTER TABLE `PRODUTOS` DROP FOREIGN KEY `PRODUTOS_ibfk_2`;

-- DropForeignKey
ALTER TABLE `SERIE` DROP FOREIGN KEY `SERIE_ibfk_1`;

-- AddForeignKey
ALTER TABLE `CATEGORIA` ADD CONSTRAINT `CATEGORIA_id_supercategoria_fkey` FOREIGN KEY (`id_supercategoria`) REFERENCES `CATEGORIA`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CLIENTE_ENDERECO` ADD CONSTRAINT `CLIENTE_ENDERECO_cpf_cliente_fkey` FOREIGN KEY (`cpf_cliente`) REFERENCES `CLIENTE`(`cpf`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CLIENTE_ENDERECO` ADD CONSTRAINT `CLIENTE_ENDERECO_endereco_id_fkey` FOREIGN KEY (`endereco_id`) REFERENCES `ENDERECO`(`numero_cep`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMPRA` ADD CONSTRAINT `COMPRA_endereco_entrega_id_fkey` FOREIGN KEY (`endereco_entrega_id`) REFERENCES `ENDERECO`(`numero_cep`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMPRA` ADD CONSTRAINT `COMPRA_cpf_cliente_fkey` FOREIGN KEY (`cpf_cliente`) REFERENCES `CLIENTE`(`cpf`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMPRA_PRODUTOS` ADD CONSTRAINT `COMPRA_PRODUTOS_id_compra_fkey` FOREIGN KEY (`id_compra`) REFERENCES `COMPRA`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `COMPRA_PRODUTOS` ADD CONSTRAINT `COMPRA_PRODUTOS_id_produtos_fkey` FOREIGN KEY (`id_produtos`) REFERENCES `PRODUTOS`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUTOS` ADD CONSTRAINT `PRODUTOS_id_categoria_fkey` FOREIGN KEY (`id_categoria`) REFERENCES `CATEGORIA`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PRODUTOS` ADD CONSTRAINT `PRODUTOS_id_modelo_fkey` FOREIGN KEY (`id_modelo`) REFERENCES `MODELO`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SERIE` ADD CONSTRAINT `SERIE_id_modelo_fkey` FOREIGN KEY (`id_modelo`) REFERENCES `MODELO`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- RenameIndex
ALTER TABLE `CATEGORIA` RENAME INDEX `id_supercategoria` TO `CATEGORIA_id_supercategoria_idx`;

-- RenameIndex
ALTER TABLE `CLIENTE_ENDERECO` RENAME INDEX `cpf_cliente` TO `CLIENTE_ENDERECO_cpf_cliente_idx`;

-- RenameIndex
ALTER TABLE `CLIENTE_ENDERECO` RENAME INDEX `endereco_id` TO `CLIENTE_ENDERECO_endereco_id_idx`;

-- RenameIndex
ALTER TABLE `COMPRA` RENAME INDEX `cpf_cliente` TO `COMPRA_cpf_cliente_idx`;

-- RenameIndex
ALTER TABLE `COMPRA` RENAME INDEX `endereco_entrega_id` TO `COMPRA_endereco_entrega_id_idx`;

-- RenameIndex
ALTER TABLE `COMPRA_PRODUTOS` RENAME INDEX `id_compra` TO `COMPRA_PRODUTOS_id_compra_idx`;

-- RenameIndex
ALTER TABLE `COMPRA_PRODUTOS` RENAME INDEX `id_produtos` TO `COMPRA_PRODUTOS_id_produtos_idx`;

-- RenameIndex
ALTER TABLE `PRODUTOS` RENAME INDEX `id_categoria` TO `PRODUTOS_id_categoria_idx`;

-- RenameIndex
ALTER TABLE `PRODUTOS` RENAME INDEX `id_modelo` TO `PRODUTOS_id_modelo_idx`;

-- RenameIndex
ALTER TABLE `SERIE` RENAME INDEX `id_modelo` TO `SERIE_id_modelo_idx`;
